#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-requests_oauthlib
Version  : 1.3.1
Release  : 30
URL      : https://files.pythonhosted.org/packages/95/52/531ef197b426646f26b53815a7d2a67cb7a331ef098bb276db26a68ac49f/requests-oauthlib-1.3.1.tar.gz
Source0  : https://files.pythonhosted.org/packages/95/52/531ef197b426646f26b53815a7d2a67cb7a331ef098bb276db26a68ac49f/requests-oauthlib-1.3.1.tar.gz
Summary  : OAuthlib authentication support for Requests.
Group    : Development/Tools
License  : ISC
Requires: pypi-requests_oauthlib-license = %{version}-%{release}
Requires: pypi-requests_oauthlib-python = %{version}-%{release}
Requires: pypi-requests_oauthlib-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(oauthlib)
BuildRequires : pypi(requests)
BuildRequires : pypi(requests_mock)

%description
Requests-OAuthlib |build-status| |coverage-status| |docs|
=========================================================

%package license
Summary: license components for the pypi-requests_oauthlib package.
Group: Default

%description license
license components for the pypi-requests_oauthlib package.


%package python
Summary: python components for the pypi-requests_oauthlib package.
Group: Default
Requires: pypi-requests_oauthlib-python3 = %{version}-%{release}

%description python
python components for the pypi-requests_oauthlib package.


%package python3
Summary: python3 components for the pypi-requests_oauthlib package.
Group: Default
Requires: python3-core
Provides: pypi(requests_oauthlib)
Requires: pypi(oauthlib)
Requires: pypi(requests)

%description python3
python3 components for the pypi-requests_oauthlib package.


%prep
%setup -q -n requests-oauthlib-1.3.1
cd %{_builddir}/requests-oauthlib-1.3.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1643584459
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-requests_oauthlib
cp %{_builddir}/requests-oauthlib-1.3.1/LICENSE %{buildroot}/usr/share/package-licenses/pypi-requests_oauthlib/44d0ccfd43c5941abf44e8e5dba5e198a1b4badd
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-requests_oauthlib/44d0ccfd43c5941abf44e8e5dba5e198a1b4badd

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
